spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bisdb
    username: bis
    password: bis
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
